version: '3.5'

services:
  centralinteligencia:
    image: centralinteligencia:v1.0.0
    container_name: centralinteligencia
    env_file: centralinteligencia/enrironment.env
    build:
        context: ./centralinteligencia
        dockerfile: Dockerfile
    ports:
      - '9090:9090'
    restart: always
    
  satelites:
    image: satelites:v1.0.0
    container_name: satelites
    build:
        context: ./satelites
        dockerfile: Dockerfile
    restart: always
