
INSERT INTO MELI.SATELITES(NAME, POSITION_X, POSITION_Y) VALUES ('kenobi', -500, -200);
INSERT INTO MELI.SATELITES(NAME, POSITION_X, POSITION_Y) VALUES ('skywalker', 100, -100);
INSERT INTO MELI.SATELITES(NAME, POSITION_X, POSITION_Y) VALUES ('sato', 500, 100);