
DELETE FROM MELI.SATELITES;

INSERT INTO MELI.SATELITES(NAME, POSITION_X, POSITION_Y, WORKING) VALUES ('kenobi', -500, -200, 'Y');
INSERT INTO MELI.SATELITES(NAME, POSITION_X, POSITION_Y, WORKING) VALUES ('skywalker', 100, -100, 'Y');
INSERT INTO MELI.SATELITES(NAME, POSITION_X, POSITION_Y, WORKING) VALUES ('sato', 500, 100, 'Y');