
CREATE TABLE IF NOT EXISTS MELI.SATELITES (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR2(64 BYTE) NOT NULL,
    DISTANCE DECIMAL(8, 5) NULL,
    POSITION_X DECIMAL(8, 5) NULL,
    POSITION_Y DECIMAL(8, 5) NULL,
    WORKING CHAR NOT NULL DEFAULT 'Y',
    PRIMARY KEY (ID),
    UNIQUE KEY NAME_UNIQUE_KEY (NAME)
);
GRANT SELECT, UPDATE, DELETE, INSERT ON MELI.SATELITES TO SA;