
CREATE TABLE IF NOT EXISTS MELI.SATELITES (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    NAME VARCHAR2(64 BYTE) NOT NULL,
    DISTANCE DECIMAL(8, 5) NULL,
    POSITION_X DECIMAL(8, 5) NULL,
    POSITION_Y DECIMAL(8, 5) NULL,
    MESSAGE VARCHAR2(2048 BYTE) NULL,
    WORKING CHAR NOT NULL DEFAULT 'Y',
    PRIMARY KEY (ID),
    UNIQUE KEY NAME_UNIQUE_KEY (NAME)
);
GRANT SELECT, UPDATE, DELETE, INSERT ON MELI.SATELITES TO SA;


CREATE TABLE IF NOT EXISTS MELI.SATELITES_LOGS (
    ID INT(11) NOT NULL AUTO_INCREMENT,
    ID_SATELITE INT(11) NOT NULL,
    DISTANCE DECIMAL(8, 5) NULL,
    POSITION_X DECIMAL(8, 5) NULL,
    POSITION_Y DECIMAL(8, 5) NULL,
    MESSAGE VARCHAR2(2048 BYTE) NULL,
    WORKING CHAR NOT NULL DEFAULT 'Y',
    DTLU DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);
GRANT SELECT, UPDATE, DELETE, INSERT ON MELI.SATELITES_LOGS TO SA;